// <auto-generated />
using HobbiesGroup7.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HobbiesGroup7.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20211201190739_Reid")]
    partial class Reid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HobbiesGroup7.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamMemberId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamMemberId = 1,
                            Bio = "I am a 4th year IT student and an aspiring software developer/architect.",
                            HobbyDescription = "I like playing rock and metal music on guitar, keyboard and drums.",
                            HobbyTitle = "Music",
                            Name = "Dev Agrawal"
                        },
                        new
                        {
                            TeamMemberId = 2,
                            Bio = "I am a third year student studying IT with a specialization in Software Development",
                            HobbyDescription = "I like playing competitive shooters such as Halo, Overwatch, and Valorant.",
                            HobbyTitle = "Video Games",
                            Name = "Reid Sweeney"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
